### ISSUE TITLE
mailbag to destination

### ISSUE THREAD

**Issue by nkrabben** [UAlbanyArchives/mailbagit#226]
**Is your feature request related to a problem? Please describe.**
I often need to create a bag in a different location than my working directory.

**Describe the solution you'd like**
I'd like to mailbag to a destination like `--destination path/to/staging/mailbags/` or `-m /path/to/staging/mailbags/mailbag.name`

**Describe alternatives you've considered**
I could move it after the fact
`mailbagit ... -m mailbagname | mv mailbagname path/to/staging/mailbags/`

**Comment by gwiedeman** [comment]
Draft implementation in [moving_options-226-227](https://github.com/UAlbanyArchives/mailbagit/tree/moving_options-226-227). Just needs fixing tests, more testing with companion files, and updated docs.

**Comment by gwiedeman** [comment]
Implemented by #229
