### ISSUE TITLE
FileNotFoundError results in mailbagit exiting before finishing

### ISSUE THREAD

**Issue by laissezfarrell** [UAlbanyArchives/mailbagit#234]
**Describe the bug**
When mailbagit encounters an object whose filename includes characters not allowed by the host file system, it throws a FileNotFoundError and stops processing the rest of the input email file.

Running mailbagit over an mbox file exported from Apple Mail (ca. 2018), at message 4895 (of approx 6000), received this error: 
```
Traceback (most recent call last):
  File "/usr/local/bin/mailbagit", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/mailbagit/__init__.py", line 251, in cli
    main(args)
  File "/usr/local/lib/python3.11/site-packages/mailbagit/__init__.py", line 313, in main
    return c.generate_mailbag()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mailbagit/controller.py", line 174, in generate_mailbag
    controller.writeAttachmentsToDisk(self.args.dry_run, attachments_dir, message)
  File "/usr/local/lib/python3.11/site-packages/mailbagit/helper/controller.py", line 107, in writeAttachmentsToDisk
    f = open(attachment_path, "wb")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/arrow_access_derivatives/2017_apple-mail-inbox/data/attachments/4895/Can changes in climate cause conflict?            \r.ics'
```

Mailbagit then stopped processing the rest of the MBOX file. The resulting mailbag does not include mailbag.csv or the final manifest-sha256 and manifest-sha512 files.

**To Reproduce**
Ran the following command: 
`mailbagit /path/to/files/ -m /data/output/2017_apple-mail-inbox -i mbox -d eml pdf -k`

**Expected behavior**
I expected mailbagit to log the error and continue processing the rest of the messages in the MBOX file.

**Screenshots**

**Environment (please complete the following information):**
_ GUI or command line?: command line
- OS: Windows host running the mailbagit workshop Docker container
- Python version: 3.11.2

**Additional context**
My wild guess is that the attachment's filename includes characters that are not allowed by either the Windows host or the container.

**Comment by gwiedeman** [comment]
Fixed in v0.6.1 with #236
