### ISSUE TITLE
Logging could have the option to output to a file, particularly for accessibility purposes

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/mailbagit#83]
## The problem the component solves

Currently, the mailbag logger outputs to the console based on the MAILBAG_LOG_LEVEL environment variable. An output file would greatly improve the experience when using mailbagit with a screen reader.

## Relevant part of mailbag spec?
n/a

## Type of component

- [x] Core
- [ ] Input
- [ ] Attachments
- [ ] Derivatives conversion
- [ ] Reporting/Exporting
- [ ] GUI
- [ ] Distribution

## Expected contribution

- [x] Pull Request
- [ ] Comment with proposed solution

## Major challenges or things to keep in mind

[ArchivesSnake ](https://github.com/archivesspace-labs/ArchivesSnake#logging) does this with some config. This could be another flag, or just another environment variable that overrides the console to a file?

**Comment by gwiedeman** [comment]
This is trickier than I expected with our current structlog implementation. I also discovered messing with this that there are also logs from `extract_msg` and `bagit-python` which are not currently being shown to the console. Should they? Maybe just on debug?

Also, we are currently excluding the `bagit-python` `--log` and `--quiet` args as they're not set up to do anything. As I user I would expect setting `--log path/to/file.log` to send all current logs to a file based on `$MAILBAG_LOG_LEVEL` as its currently set up. `--quiet` might override `$MAILBAG_LOG_LEVEL` and set it to error, though we may just want to exclude that.

We're also working on [showing progress](https://github.com/UAlbanyArchives/mailbag/pull/148) to `stdout`, which I don't _think_ would get log to a file with `--log` and would still show in stdout but I'm not totally confident with that.

**Comment by pobocks** [comment]
So, I've been poking around at this design-wise - I think the log level makes sense as you've described.  My plan for now is to basically do the following:

1. set it up so logging is in a separate handler and doesn't affect other config
2. logging should basically be left unconfigured and default to very low emission levels if mailbagit is pulled in as a library
3. if mailbagit is run as a script (i.e. either of the two entrypoint methods are run) then configure logging basically the same way as ArchivesSnake - i.e. a fairly complete evented logging setup.

**Comment by gwiedeman** [comment]
Addressed by #207
